# Generated by Django 5.1.4 on 2025-01-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='starslog',
            table='students_starslog',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students_student',
        ),
    ]
