# Generated by Django 5.1.4 on 2025-01-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_adminuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='students_user',
        ),
    ]
